name: Build Jekyll Site Locally

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main # Replace with your default branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1 # Use the Ruby version compatible with GitHub Pages
        bundler-cache: true

    - name: Install Dependencies
      run: |
        bundle install

    - name: Build Jekyll Site
      run: |
        bundle exec jekyll build

    - name: Upload Site as Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: jekyll-site
        path: _site